syntax = "proto3";

package analyzer;

service AnalyzerService {
  rpc UploadAndUnzip(UploadRequest) returns (UploadResponse);
  rpc AnalyzeCVs (AnalyzeCVRequest) returns (AnalyzeCVResponse);
}

message UploadRequest {
  string filePath = 1;
}

message UploadResponse {
  string message = 1;
  string outputDir = 2;
}

message AnalyzeCVRequest {
  string jobTitle = 1;
  string jobDescription = 2;
  repeated string requiredSkills = 3;
  int32 experienceLevel = 4;
  string extraContext = 5;
  repeated string fileKeys = 6;
}

message AnalysisResult {
  string fileName = 1;
  string result = 2;
  string status = 3;
  string error = 4;
}

message AnalyzeCVResponse {
  repeated AnalysisResult results = 1;
}